---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

 
**Study title: Diet based Minimal Microbiome Db-MM**     
Authors: Sudarshan A. Shetty<sup>1</sup>, Ben Kuipers<sup>1</sup>, Siavash Atashgahi<sup>1</sup>, Steven Aalvink<sup>1</sup>, Hauke Smidt<sup>1</sup>, Willem M. de Vos<sup>1,2</sup>*  

  
<sup>1</sup>Laboratory of Microbiology, Wageningen University and Research, Wageningen, The Netherlands.   
<sup>2</sup>Human Microbiome Research Program, Faculty of Medicine, University of Helsinki, Helsinki, Finland.
 

Correspondence: Willem M. de Vos; willem.devos[@]wur[dot]nl 

This repository contains codes for analysis done in the research article by Shetty, S.A., Kuipers, B., Atashgahi, A., Aalvink, S., Smidt, H., de Vos WM. (2020).Inter-species Metabolic Interactions in a Minimal Human Gut Microbiome of Core Bacteria. [in prep](XXX). 


GitHub repo: [mibwurrepo/Shetty_et_al_DbMM10](https://github.com/mibwurrepo/Shetty_et_al_DbMM10)  
Author: Sudarshan A. Shetty
Contact: sudarshanshetty9[at]gmail[dot]com
